services:
  db:
    image: postgres:latest
    container_name: db-taskManager
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-taskManager-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    build:
      context: .
    container_name: app-taskManager
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8080:8080'

volumes:
  db-taskManager-volume:
    name: db-taskManager-volume


